---
- name: "Testing all the servers connectivity and python interpreter"
  hosts: all
# vars:
#   DR_NAME: site_dr
  roles:
    # - update
    # - var_test
    # - franklinkim.vim
    # - punit-vim8
    # - punit-facts
