---
- name: update the system
  yum:
    name: "*"
    state: latest
    skip_broken: yes
  when:
    - ansible_os_family == 'RedHat'
    - ansible_distribution_major_version == '7'

- include: vim_req.yml
  tags: vim_req
  when:
    - ansible_os_family == 'RedHat'
    - ansible_distribution_major_version == '7'

- include: vim_check.yml
  tags: vim_check

- include: redhat7.yml
  when:
    - ansible_os_family == 'RedHat'
    - ansible_distribution_major_version == '7'
  tags: redhat7

- include: redhat8.yml
  when:
    - ansible_distribution_major_version == '8'
    - ansible_os_family == 'RedHat'
  tags: redhat8

- include: vim_config.yml
  tags: vim_config
