---
# tasks file for punit-facts
- name: Gathering facts of host {{ ansible_hostname }}
  setup:
    gather_subset: all
  register: g_fact

- name: Creating facts files to /files directory.
  file:
    dest: /home/pgrewal/Project-Ansible//files/{{ ansible_hostname }}.yaml
    state: absent
  delegate_to: localhost

- name: Creating facts files to /files directory.
  lineinfile:
    dest: /home/pgrewal/Project-Ansible//files/{{ ansible_hostname }}.yaml
    create: yes
    line: "{{ g_fact | to_nice_yaml }}"
  delegate_to: localhost
