---
# tasks file for punit-facts
- name: Gathering facts of hosts.
  setup:
    gather_subset: all
  register: g_fact

- name: Creating facts files to /facts directory.
  file:
    dest: /home/pgrewal/Project-Ansible//facts/{{ ansible_hostname }}.json
    state: absent
  delegate_to: localhost

- name: Creating facts files to /facts directory.
  lineinfile:
    dest: /home/pgrewal/Project-Ansible//facts/{{ ansible_hostname }}.json
    create: yes
    line: "{{ g_fact | to_nice_json }}"
  delegate_to: localhost

- name: Facts check for hosts
  debug:
    msg: The package to install on {{ ansible_hostname }}.
