---
# tasks file for punit-facts
- name: Gathering facts of hosts.
  setup:
    gather_subset: all
  register: g_fact

- name: Deleting old facts of host {{ ansible_hostname }}.
  file:
    dest: /home/pgrewal/Project-Ansible//facts/{{ ansible_hostname }}.json
    state: absent
  delegate_to: localhost

- name: Generating facts of host {{ ansible_hostname }}.
  lineinfile:
    dest: /home/pgrewal/Project-Ansible//facts/{{ ansible_hostname }}.json
    create: yes
    line: "{{ g_fact | to_nice_json }}"
    mode: '0644'
  delegate_to: localhost

- name: Facts Validation
  debug:
    msg: hostname --{{ ansible_hostname }}--
